spring:
  application:
    name: demo-hydrostation-developer
server:
  port: 8772
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
  instance:
    preferIpAddress: true